build:
  version: "1.0"

products:
  message: "Welcome to EcomEase products related Production APIs "
  contactDetails:
    name: "Sahil Anower - Developer"
    email: "sahilanower2@gmail.com"
  onCallSupport:
    - (+91) 6289208895
